### ISSUE TITLE
Identify records from MS errors

### ISSUE THREAD

**Issue by rappen** [rappen/PluginTraceViewer#195]
These from MS error messages should be possible to identify the record.

![image](https://github.com/rappen/PluginTraceViewer/assets/2572253/4e29bc15-c5c0-4d9b-9657-a50f1e14a192)

Ref #193 

---
- Deployment: Online
- DB Version: 9.2.24053.188
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.12.68
- Tool Version: 1.2024.6.2

**Comment by rappen** [comment]
Example:

```
*** Error: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault] ***
System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: More than one concurrent Share requests detected for an Entity ec8c15c8-c19b-f111-b8db-7ced8d417cd0 and ObjectTypeCode 10980. (Fault Detail is equal to Exception details: 
ErrorCode: 0x80048105
Message: More than one concurrent Share requests detected for an Entity ec8c15c8-c19b-f111-b8db-7ced8d417cd0 and ObjectTypeCode 10980.
TimeStamp: 2026-08-19T11:33:38.0000000Z
OriginalException: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: More than one concurrent Share requests detected for an Entity ec8c15c8-c19b-f111-b8db-7ced8d417cd0 and ObjectTypeCode 10980. (Fault Detail is equal to Exception details: 
ErrorCode: 0x80048105
Message: More than one concurrent Share requests detected for an Entity ec8c15c8-c19b-f111-b8db-7ced8d417cd0 and ObjectTypeCode 10980.
TimeStamp: 2026-08-19T11:33:38.9763713Z
--
Exception details: 
ErrorCode: 0x80048105
Message: More than one concurrent Share requests detected for an Entity ec8c15c8-c19b-f111-b8db-7ced8d417cd0 and ObjectTypeCode 10980.
TimeStamp: 2026-08-19T11:33:38.9763713Z
--
Exception details: 
ErrorCode: 0x80044339
Message: Cannot use this database resource because an...).
   at Microsoft.CDSRuntime.SandboxWorker.SandboxCallbackService.<>c__DisplayClass16_1.<ExecuteStreamingCallBack>b__1(ExecuteRequest response)
   at Microsoft.CDSRuntime.SandboxWorker.SandboxCallbackService.GrpcClientSendAndReceive(ExecuteResponse executeResponse, Func`2 isTerminalResponse)
   at Microsoft.CDSRuntime.SandboxWorker.SandboxCallbackService.<>c__DisplayClass16_0.<ExecuteStreamingCallBack>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.CDSRuntime.SandboxWorker.SandboxCallbackService.ExecuteStreamingCallBack(Func`2 callback, Func`2 isTerminalChunk, Func`2 HandleClientException)
   at Microsoft.CDSRuntime.SandboxWorker.SandboxOrganizationService.Execute(String operation, ByteString serializedRequest, Assembly proxyTypes, Object traceSettings)
   at Microsoft.CDSRuntime.SandboxWorker.SandboxOrganizationServiceWrapper.<>c__DisplayClass24_0.<ExecuteInternal>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)
   at Microsoft.CDSRuntime.SandboxWorker.SandboxOrganizationServiceWrapper.ExecuteInternal(OrganizationRequest request)
   at CRMK.CrmSdk.Base.ContainerBase.Execute(OrganizationRequest request)
   at CRMK.CrmSdk.Base.ContainerBase.GrantAccess(EntityReference entity, EntityReference principal, AccessRights rights)
   at......
```

Exception example:
```
System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Unhandled System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault] in PluginBase: More than one concurrent Share requests detected for an Entity ec8c15c8-c19b-f111-b8db-7ced8d417cd0 and ObjectTypeCode 10980.
at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricGrpcClient.ExecutePluginInternal(IRemotePluginRequest pluginRequest, ExecuteRequest executeRequest, Guid executionId, ISandboxFabricDuplexCommunicationHandler communicationHandler, Boolean returnTraceInfo, Guid organizationId, SandboxFabricCallTracker sandboxFabricCallTracker) +0x5d7
at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricGrpcClient.ExecutePlugin(IRemotePluginRequest pluginRequest, IPluginExecutionContext executionContext, IPluginTracingService pluginTracingService, ISandboxFabricDuplexCommunicationHandler communicationHandler, ISet`1 earlySerializedPropertiesList, SandboxFabricCallTracker sandboxFabricCallTracker, ISandboxMemoryStreamProvider memoryStreamProvider) +0x327
at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricCodeUnit.ExecutePlugin(ILifetimeScope scope, IExecutionContext context, ISandboxFabricDuplexCommunicationHandler communicationHandler, ISandboxClientSettings sandboxClientSettings, SandboxFabricCallTracker& sandboxFabricCallTracker, ISandboxFabricGrpcClient sandboxFabricGrpcClient, ISandboxMemoryStreamProvider memoryStreamProvider) +0x16
at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricCodeUnit.Execute(ILifetimeScope scope, IExecutionContext context, SandboxFabricCallTracker& sandboxFabricCallTracker, ISandboxMemoryStreamProvider memoryStreamProvider) +0xf8
at Castle.Proxies.Invocations.ISandboxFabricCodeUnit_Execute.InvokeMethodOnTarget() +0x13
at Castle.DynamicProxy.AbstractInvocation.Proceed() +0x2d
at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricPluginTraceInterceptor.Intercept(IInvocation invocation, IExecutionContext context, SandboxFabricCallTracker sandboxFabricCallTracker) +0x1f
```
